# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4238bb7bc2a00887e0cd788aa8706f54243274f0b91155217f68a410a770bd22d42019be3c96763d106d5083cfac43ee0ff982e833ba35d3059f330a9615e073

test:
  secret_key_base: dff08b42fe9977ee5758aace48965847d261327eb04d5438e97323cad987aed2802b8af4937896a587009aeab4431610a6d7ff7ab1821c305b29234f4c994f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
